### ISSUE TITLE
Viewing Key byte sequence is incorrect

### ISSUE THREAD

**Issue by zmanian** [plutomonkey/zcash-vanity#5]
<img width="722" alt="screen shot 2018-01-07 at 1 33 00 pm" src="https://user-images.githubusercontent.com/93434/34649615-13f7bef0-f3b3-11e7-8bf6-b0814605023c.png">

Currently, https://github.com/plutomonkey/zcash-vanity/blob/master/src/address.rs#L50-L51 is doing [PREFIX][sk_enc][a_pk] the protocol doc specifes the reverse.

Pull request coming in a sec.

**Comment by jasondavies** [comment]
Fixed in 0.2.6.  Thanks!
