### ISSUE TITLE
failed to compile "zcash-vanity v0.2.7"

### ISSUE THREAD

**Issue by 4arda** [plutomonkey/zcash-vanity#8]
error: failed to run custom build command for `ring v0.13.0-alpha`
process didn't exit successfully: `C:\Users\todhiba\AppData\Local\Temp\cargo-install.f6aGmdqTCpWe\release\build\ring-8de6a6c4297493e9\build-script-build` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `zcash-vanity v0.2.7`, intermediate artifacts can be found at `C:\Users\todhiba\AppData\Local\Temp\cargo-install.f6aGmdqTCpWe`

Caused by:
  build failed

**Comment by jasondavies** [comment]
Sounds like an issue with building `ring`.  Which platform are you targeting?  I’m guessing `x86_64-pc-windows-msvc`?

**Comment by 4arda** [comment]
Yes i'm using the x_64-windows-msvc Platform

**Comment by jasondavies** [comment]
I’ve just published version 0.2.8, which should hopefully be more portable as it uses the `rand` crate instead of `ring`.
